// Built-in Workspace templates. Content is Plate JSON; creating from a template copies it.
type Node = { type: string; children: { text: string }[]; checked?: boolean; [key: string]: unknown };
const h = (type: string, text: string): Node => ({ type, children: [{ text }] });
const p = (text = ""): Node => ({ type: "p", children: [{ text }] });
const todo = (text: string): Node => ({ type: "todo_item", checked: false, children: [{ text }] });
const hr = (): Node => ({ type: "hr", children: [{ text: "" }] });
const bullet = (text = "", indent = 1): Node => ({ type: "p", indent, listStyleType: "disc", children: [{ text }] });
const num = (text = "", indent = 1): Node => ({ type: "p", indent, listStyleType: "decimal", children: [{ text }] });
const quote = (text: string): Node => ({ type: "blockquote", children: [{ text }] });

// --- Live-app block builders (Project Tracker / Kanban / Calendar) ---
// Deterministic ids (no runtime randomness) — unique within a document is all that's required.
let _seq = 0;
const nid = (prefix: string) => `${prefix}-${(_seq += 1)}`;

// MJG brand: gold-stepped + ink; statuses avoid green per brand.
const GOLD = "#C9A46E", BRONZE = "#B58F55", DEEP_GOLD = "#9E7A46", INK = "#3f3a34", RED = "#9B2F2E";
const TRACKER_STATUSES = [
  { label: "Upcoming", color: GOLD },
  { label: "In Progress", color: RED },
  { label: "Complete", color: INK },
];

const trackerRow = (name: string, opts: { owner?: string; status?: string; deadline?: string } = {}) =>
  ({ id: nid("row"), name, home: "workspace", recordId: null, href: null, ownerId: null, ownerName: opts.owner ?? "", status: opts.status ?? null, deadline: opts.deadline ? { date: opts.deadline } : null, attachment: null });
const projectTracker = (rows: ReturnType<typeof trackerRow>[]): Node =>
  ({ type: "project_tracker", statuses: TRACKER_STATUSES, rows, children: [{ text: "" }] });

const card = (text: string) => ({ id: nid("card"), text });
const column = (title: string, color: string, cards: string[] = []) => ({ id: nid("col"), title, color, cards: cards.map(card) });
const kanban = (columns: ReturnType<typeof column>[]): Node =>
  ({ type: "kanban_board", columns, children: [{ text: "" }] });

const calendar = (events: { date: string; title: string }[] = []): Node =>
  ({ type: "doc_calendar", events: events.map((e) => ({ id: nid("ev"), date: e.date, title: e.title, color: RED })), children: [{ text: "" }] });

export type WorkspaceTemplate = {
  id: string;
  name: string;
  description: string;
  category: string;
  content: Node[];
};

export const WORKSPACE_TEMPLATES: WorkspaceTemplate[] = [
  {
    id: "blank",
    name: "Blank document",
    description: "Start from scratch.",
    category: "General",
    content: [p("")],
  },
  {
    id: "meeting-notes",
    name: "Client Meeting Notes",
    description: "Capture a client conversation, decisions, and follow-ups.",
    category: "Meetings",
    content: [
      h("h1", "Client Meeting Notes"),
      p("Date: "),
      p("Attendees: "),
      h("h2", "Purpose"),
      p(""),
      h("h2", "Discussion"),
      p(""),
      h("h2", "Decisions"),
      p(""),
      h("h2", "Follow-up tasks"),
      todo(""),
      todo(""),
      h("h2", "Next appointment"),
      p(""),
    ],
  },
  {
    id: "blueprint-review",
    name: "Stewardship Blueprint Review",
    description: "Review a client's Blueprint across the key areas.",
    category: "Stewardship",
    content: [
      h("h1", "Stewardship Blueprint Review"),
      p("Client: "),
      p("Completion status: "),
      h("h2", "Faith"),
      p(""),
      h("h2", "Family"),
      p(""),
      h("h2", "Finances"),
      p(""),
      h("h2", "Future"),
      p(""),
      h("h2", "Advisor observations"),
      p(""),
      h("h2", "Recommended next steps"),
      todo(""),
      todo(""),
    ],
  },
  {
    id: "onboarding",
    name: "New Client Onboarding",
    description: "Onboard a new client with a checklist.",
    category: "Stewardship",
    content: [
      h("h1", "New Client Onboarding"),
      p("Client: "),
      p("Assigned advisor: "),
      h("h2", "Onboarding checklist"),
      todo("Welcome communication sent"),
      todo("Required documents collected"),
      todo("Account access set up"),
      todo("First appointment scheduled"),
      h("h2", "Open questions"),
      p(""),
    ],
  },
  {
    id: "team-agenda",
    name: "Team Meeting Agenda",
    description: "Run a focused team meeting.",
    category: "Meetings",
    content: [
      h("h1", "Team Meeting Agenda"),
      p("Date: "),
      p("Attendees: "),
      h("h2", "Updates"),
      p(""),
      h("h2", "Discussion topics"),
      p(""),
      h("h2", "Decisions"),
      p(""),
      h("h2", "Assigned actions"),
      todo(""),
      h("h2", "Next meeting"),
      p(""),
    ],
  },
  {
    id: "team-meeting-review",
    name: "Team Meeting Review",
    description: "Live team-meeting overview of every active job — status, dates, financials, issues, action items, and procurement.",
    category: "Meetings",
    content: [
      h("h1", "Team Meeting Review"),
      p("Meeting Date & Time: "),
      p("Project Coordinator: "),
      p("Attendees: "),
      hr(),

      h("h2", "Jobs Overview"),
      p("At-a-glance status of every active job. Owner = PM · Deadline = current completion date. Use “Add row” for each job and the Owner column to assign a PM."),
      projectTracker([
        trackerRow("Job — ", { status: "In Progress" }),
        trackerRow("Job — ", { status: "Upcoming" }),
      ]),
      hr(),

      h("h2", "Job Review"),
      quote("Duplicate this Job Review section for each active job discussed."),
      p("Job Name: "),
      p("Job Number: "),
      p("Status: "),
      p("Original Completion Date: "),
      p("Current Completion Date: "),
      p("Financial Status (as of date & time): "),

      h("h3", "Issues"),
      bullet(""),
      bullet(""),

      h("h3", "Action Items"),
      p("Add an item per row, assign staff/contacts in Owner (type a name or add a Users / Connect column for a CMI contact), and set a due date + status."),
      projectTracker([
        trackerRow("", { status: "Upcoming" }),
        trackerRow("", { status: "Upcoming" }),
      ]),

      h("h3", "Procurement"),
      p("Track products & selections — assign a vendor in Owner, set selection/install dates in Deadline, and use “Add column” for Vendor Assignment Date and Bill/Deposit."),
      projectTracker([
        trackerRow("Product / selection — ", { status: "Upcoming" }),
        trackerRow("Product / selection — ", { status: "Upcoming" }),
      ]),
      bullet("Product / selection & dates: "),
      bullet("Install: "),
      bullet("Vendor assignment date: "),
      bullet("Bill / deposit (selection / product): "),

      h("h3", "Notes"),
      p(""),
    ],
  },
  {
    id: "weekly-workload-meetings",
    name: "Weekly Workload Meetings",
    description: "CMI's full weekly workload agenda — active projects, warranty jobs, pre-construction, leads, and company/general items.",
    category: "Meetings",
    content: [
      h("h1", "Weekly Workload Meetings"),
      p("Date: "),
      hr(),

      h("h2", "Active Project Status"),

      h("h3", "25_062_ Olson Casita"),
      bullet("Project Status: In Progress"),
      bullet("Original Completion Date: May 22nd, 2026"),
      bullet("Current Completion Date: BEN needs to update"),
      bullet("Financial: July Paid"),
      bullet("Issues / Action Items:"),
      todo("Electrical panel upgrade — need permit (in process)"),
      bullet("Punchlist items:"),
      todo("Final clean — needs to be scheduled (Mon)"),
      todo("Substantial completion"),
      todo("Photograph before move in — Ben to schedule"),
      todo("Install mirror"),
      todo("Patchback"),

      h("h3", "24_071_ Lysay Residence"),
      bullet("Project Status: In Progress"),
      bullet("Original Completion Date: Oct 1st, 2026"),
      bullet("Current Completion Date: Oct 22nd, 2026 (client wants to move in Oct 12th)"),
      bullet("Financial: July Paid"),
      bullet("Issues / Action Items:"),
      todo("Stair handrail"),
      todo("Upstairs HVAC"),
      todo("Sierra Pacific — issues"),
      todo("COI — Irish man (follow up - YH)"),
      bullet("Procurement:"),
      todo("Sink accessories — YH order items included"),
      todo("Zia tile is still backordered — eta mid-September"),

      h("h3", "25_042_ Baxter Residence"),
      bullet("Project Status: In Progress"),
      bullet("Scope: Laundry Room Renovation, Misc. Enhancements, Guest Bath Renovation, Boys Bath", 2),
      bullet("Design Partner: RnR Interior Design", 2),
      bullet("Original Completion Date: August 28th, 2026"),
      bullet("Current Completion Date: "),
      bullet("Financial: July not paid"),
      bullet("Issues / Action Items:"),
      todo("C-top installation begins — 8/20"),
      todo("ATC — 8/24-8/25"),
      todo("Wallpaper — (push it out)"),
      bullet("Procurement:"),
      todo("Release RnR — Laundry baskets YH"),

      h("h3", "25_057_ Shepherd of the Desert church"),
      bullet("Project Status: In Process"),
      bullet("Original Completion Date: "),
      bullet("Current Completion Date: "),
      bullet("Financial: July Paid (pick up check)"),
      bullet("Issues / Action Items:"),
      todo("Waiting on permit"),
      bullet("Procurement:"),

      h("h3", "25_036_ Schluter Art Sales (E Main Gallery) — $1.2M"),
      bullet("Project Status: In Progress"),
      bullet("Original Completion Date: January 15th, 2027"),
      bullet("Current Completion Date: "),
      bullet("Financial: Put pay app together"),
      bullet("Issues / Action Items:"),
      todo("Need Fireline and sprinkler submittals"),
      todo("APS electrical design"),
      bullet("Procurement:"),

      h("h3", "26_025_ Kendrick Residence (Jenny Nguyen)"),
      bullet("Project Status: Contracted"),
      bullet("Original Completion Date: 09/07/26"),
      bullet("Current Completion Date: "),
      bullet("Financial: Contracted"),
      bullet("Issues / Action Items:"),
      todo("Sample approval — this week"),
      todo("Bench installed, light fixture installed"),
      todo("Mirror needs to be ordered (Jocoran — have him measure after demo)"),
      todo("Demo to begin next week (19th)"),
      todo("Install brackets on the 20th (mirror measure/ordered ideally)"),
      todo("T.K. on the 20th"),
      bullet("Procurement — Lead times (these are still approx.):"),
      bullet("Soap Dispenser / Toilet paper holder — 9/14", 2),
      bullet("Faucet — 10/14", 2),
      bullet("Toto — 10/22", 2),

      h("h3", "26_016_ Mackay Residence"),
      bullet("Project Status: Project Kick Off, pending contract"),
      bullet("Original Completion Date: "),
      bullet("Current Completion Date: "),
      bullet("Financial: "),
      bullet("Issues / Action Items:"),
      todo("Kick off — next Friday"),
      bullet("Procurement:"),

      h("h3", "26_028_ Schott Residence"),
      bullet("Project Status: Contracted"),
      bullet("Original Completion Date: "),
      bullet("Current Completion Date: "),
      bullet("Financial: "),
      bullet("Issues / Action Items:"),
      bullet("Procurement:"),
      todo("Appliances — ordered"),
      todo("P/O in adaptive for Chris Cabinets"),
      todo("Bill — $24,000"),

      h("h3", "26_029_ VCS Offices / PM"),
      bullet("Project Management / Consulting"),
      bullet("Scope: Different process, only overseeing project", 2),
      bullet("Project Updates:", 2),
      bullet("Sprinklers are still delayed. Bugging them daily, so we are doing things backwards…", 3),
      bullet("Millwork — Done (minus toe kick that shippers snapped in half; replacement coming)", 3),
      bullet("Electrical — Done", 3),
      bullet("Fire Blocking — Done", 3),
      bullet("HVAC Rough — Done", 3),
      bullet("Office Window — Done", 3),
      bullet("Painting — 95% done (touchups at end)", 3),
      bullet("Carpet — Going in", 3),
      bullet("Epoxy flooring — Going in (12am-6am tonight)", 3),
      bullet("Doors — Half in (rest after carpet)", 3),
      bullet("Lighting — Cans over desk done; rest is in up to each controller box, to hook up to troffers/cans once ceiling is in", 3),
      bullet("Counters — tentative scheduled 8/18", 3),
      bullet("Front Window — tentative scheduled 8/20", 3),
      bullet("Ceiling grid sub on standby to start day after sprinklers are in", 3),
      bullet("Fire alarm / sensors sub on standby to start day +1 after sprinklers are in", 3),
      hr(),

      h("h2", "Angel"),
      todo("Patch back — Olson"),
      todo("Wood ceiling in dining room — Lysay"),
      todo("Paint — Baxter"),
      todo("Stucco Paint — Shepherd of the Desert"),
      todo("Roman Clay — Kendrick"),

      h("h2", "Office Items"),
      todo("Storage Organization — Shed"),
      hr(),

      h("h2", "Warranty Jobs"),
      bullet("25_052_ VCS"),
      bullet("Substantial Completion / Warranty Date: August 22nd, 2025 / August 22nd, 2027 — 1 year walk", 2),
      bullet("24_008_ Gupta Residence"),
      bullet("Substantial Completion / Warranty Date: March 15th, 2025 / March 15th, 2027 — Dream Retreats", 2),
      bullet("22_001_ Conrad Interior"),
      bullet("Substantial Completion / Warranty Date: July 18th, 2025 / July 18th, 2027 — 1 year walk, JB Friday", 2),
      bullet("24_058_ Duff Residence"),
      bullet("Substantial Completion / Warranty Date: June 6th, 2025 / June 6th, 2027", 2),
      bullet("25_010_ Stein"),
      bullet("Substantial Completion / Warranty Date: July 18th, 2025 / July 18th, 2027", 2),
      bullet("24_023_ Ahearn ADU"),
      bullet("Substantial Completion / Warranty Date: February 14th, 2025 / February 14th, 2027", 2),
      bullet("24_047_ Gupta landscape"),
      bullet("Substantial Completion / Warranty Date: April 4th, 2025 / April 4th, 2027", 2),
      bullet("24_075_ Rosman ADU"),
      bullet("Substantial Completion / Warranty Date: February 20th, 2025 / February 20th, 2027 — 6-month call, Ben", 2),
      bullet("24_060_ Stanley Residence"),
      bullet("Substantial Completion / Warranty Date: Feb 13th, 2026 / Feb 13th, 2028", 2),
      bullet("24_066_ Laidig Residence"),
      bullet("Substantial Completion / Warranty Date: Jan 9th, 2026 / January 9th, 2028", 2),
      bullet("24_031_ Nielsen Residence"),
      bullet("Substantial Completion / Warranty Date: July 10th, 2026 / July 10th, 2028", 2),
      hr(),

      h("h2", "Pre-Construction / Design"),
      h("h3", "25_045_ Dredge Roig Residence"),
      bullet("Project Status: "),
      bullet("Scope: Primary Suite Addition and Misc. Interior Improvements"),
      bullet("Design Partner: Craydl, RnR Design"),
      bullet("Project Notes:"),
      bullet("Interior Design Kick-Off 7/24", 2),
      bullet("Submitted for permit by end of September", 2),
      h("h3", "26_027_ Coronado Addition"),
      bullet("Garth is going to give us updated bid / construction set"),
      hr(),

      h("h2", "Active Budgets / Pre-Construction Proposals"),
      bullet("26_001_ Bebeau Residence — $1M Exeter"),
      bullet("Client to circle back", 2),
      bullet("26_006_ Livak Residence — $1M–$2M"),
      bullet("BF meeting on Thursday next week", 2),
      bullet("26_017_ DeConzo Residence"),
      bullet("BF follow up", 2),
      bullet("26_030_ Lillie Residence"),
      bullet("Presented", 2),
      bullet("26_034_ Hines Residence — Historic Remodel and Addition, Encanto"),
      bullet("As-Built Processing in Matterport", 2),
      bullet("Meeting tomorrow", 2),
      bullet("26_035_ Waltrup Residence — 2nd Story Addition, McCormick Ranch"),
      bullet("3D Scan yesterday — BF met yesterday", 2),
      bullet("BF to follow up", 2),
      bullet("26_036_ McGaffin Residence — Interior Remodel, Cactus Corridor"),
      bullet("Eric and Lauren", 2),
      bullet("As-Built Processing in Matterport", 2),
      bullet("BF to follow up", 2),
      bullet("26_037_ Jimenez Residence — Interior Remodel and Addition (Partially Complete), Chandler"),
      bullet("BF to work through", 2),
      hr(),

      h("h2", "Active Leads Status Updates"),
      bullet("26_013_ Garfield Casita"),
      bullet("Ben — send client info to contract engineering initial evaluation", 2),
      bullet("26_019_ Latino Residence — Waiting on client"),
      bullet("26_026_ Young Residence — Waiting on client"),
      bullet("26_004_ Zack Residence"),
      bullet("HOA preliminary approval; already working with an architect, Ed Chavez, who will let us know when design is complete", 2),
      bullet("Pend. Design", 2),
      bullet("26_033_ TI Project"),
      bullet("26_0xx_ xxxxx"),
      hr(),

      h("h2", "Long Term Lead Status Updates"),
      bullet("25_003_ Weisenburger Residence — Lead Status: Client Hold"),
      bullet("Sending over landscape design / holding off for a few years on main home", 2),
      bullet("25_026_ Harris Residence — Lead Status: F&F, BF building budget"),
      bullet("25_031_ Rehse Residence (Addition) — BF to follow up"),
      bullet("25_038_ Lively Residence Casita — Lead Status: Client Hold, check in Q1 (BF to follow up)"),
      bullet("25_047_ Kaminsky Residence (4Line) — Guest House Addition + 2-car Garage"),
      bullet("Lead Status: Playing pro basketball — will reach out when more in line with moving forward (BF followed up, no response)", 2),
      bullet("25_073_ Pach Residence — Presented Initial Budget"),
      bullet("26_002_ Gropler Residence — PCH docs, looking at future purchase"),
      bullet("26_010_ Walling Residence"),
      bullet("26_012_ Donovan Residence — BF/JB initial budget review on Thursday"),
      bullet("25_059_ Zimber Residence — Project Status: Pre-Construction, Signed (BF to follow up)"),
      bullet("25_072_ Waring ADU — $600–$800 — LOI sent, BF followed up"),
      bullet("Scope: Small Misc. Interior Improvements and Casita Addition", 2),
      bullet("Design Partner: Hype Studios", 2),
      bullet("Project Notes: waiting on client to confirm", 2),
      bullet("Pre-Con Proposal (Feasibility / Estimate): 1 Bed / 1 Bath ADU, Kitchen & Living, Outdoor Patio/Kitchen, Garage and Storage; Interior door swap; architect design proposal submitted", 2),
      bullet("26_023_ Popat Residence — Pre-con sent"),
      hr(),

      h("h2", "General Items"),
      num("Builder's Risk Maintenance"),
      bullet("IH4 M320606 00 — 3/13/26 — Olson Casita, 938 W. Moreland Street, Phoenix, AZ 85007", 2),
      bullet("IH4 M342269 00 — 4/06/2026 — Lysay Residence, 8923 N 45th St., Phoenix, AZ 85028", 2),
      bullet("IH4 M405173 00 — 5/28/2026 — Baxter Residence, 6456 E Calle Del Media, Scottsdale, AZ", 2),
      bullet("IH4 M433332 00 — 6/24/26 — Shepherd of the Desert, 9400 E. Mountain View Rd, Scottsdale, AZ 85258", 2),
      bullet("IH4 M458462 00 — 7/17/2026 — VCS Offices, 6900 W Galveston St., Chandler, AZ 85226", 2),
      num("Pre-Lien Maintenance"),
      todo("Olson"),
      todo("Lysay"),
      todo("Baxter"),
      todo("Shepherd of the Desert — Needed"),
      num("Marketing Initiatives / Action Items"),
      bullet("Weekly check-in for project details to highlight", 2),
      bullet("Social Media", 2),
      bullet("Photography — Nielsen (completed?), Olson", 2),
      bullet("Print marketing upon receiving edited photos — BF to make an ad", 2),
      num("Networking Events"),
      bullet("Networking Events (Attended)", 2),
      bullet("Industry Partners Meetings", 2),
      bullet("Industry Professionals for Intros", 2),
      num("Company Items"),
      bullet("Daily Logs", 2),
      bullet("August Timecard — (END OF MONTH)", 2),
      bullet("Out of Office — Enter in Intuit for Approval / Tracking:", 2),
      bullet("Brandon — Aug 14th; Sep 14th-18th; Sep 30th-Oct 2nd (Havasupai Backpacking); Dec 3rd-8th (Elk Hunt)", 3),
      bullet("Joe — Oct 15th-23rd (North Dakota)", 3),
      bullet("Ben", 3),
      bullet("Angel", 3),
      bullet("Yovana", 3),
      num("Safety Focus Items — JB"),
      bullet("Safety Consultant", 2),
      bullet("CPR / First Aid Class — through Local 493 Trustee: $40/person CPR/AED (2-2.5 hrs); $50/person CPR/AED & First Aid (2.5-3 hrs); possible price break for groups > 30; AHA certs valid 2 years; 8-student minimum per session", 2),
      bullet("OSHA 10 — Angel (BF: when is the next session?)", 2),
      num("Rotation Topics"),
      bullet("Close-out Manuals (Nielsen / Olson)", 2),
      bullet("Wallpaper Installers — good ones", 2),
      bullet("Award Submissions:", 2),
      bullet("AZ AGC — azagc.org/about/awards-program — entry $450, deadlines Fall 2026", 3),
      bullet("ASID AZ South — asid-azs.cpjam.com — ~$175–$185 for ASID members/pros, deadlines late May 2027", 3),
      bullet("PHG Honors — phgmag.com/phg-honors — $200 first entry / $175 subsequent, deadlines March 2027", 3),
      bullet("Luxe RED Awards — luxeredawards.com — $320 early bird → $350 regular → $400 late, deadlines late Fall (closes Nov)", 3),
      bullet("Azure — awards.azuremagazine.com — $165 early bird → $275 late, opens Nov ends Feb", 3),
      bullet("AZ Masonry — azmasonry.org/excellence — ~$150 early bird, registration by end of Oct, final submittals mid-December", 3),
      bullet("Jobs to submit for awards: Duff Residence, Rosman ADU, Osborn Drive", 2),
      num("Upcoming Community Events"),
      num("Constructed Matter Events"),
      hr(),

      h("h2", "Goals // 2026"),
      todo("TBD"),
    ],
  },
  {
    id: "event-planning",
    name: "Event Planning",
    description: "Plan an event end to end.",
    category: "Marketing",
    content: [
      h("h1", "Event Planning"),
      h("h2", "Overview"),
      p("Date & venue: "),
      p("Registration goal: "),
      h("h2", "Tasks"),
      todo("Invite list"),
      todo("Marketing"),
      todo("Assets"),
      todo("Speakers"),
      h("h2", "Day-of checklist"),
      todo(""),
      h("h2", "Follow-up"),
      p(""),
    ],
  },
  {
    id: "sop",
    name: "Process / SOP",
    description: "Document a standard operating procedure.",
    category: "Operations",
    content: [
      h("h1", "Standard Operating Procedure"),
      p("Purpose: "),
      p("Owner: "),
      h("h2", "Steps"),
      todo(""),
      todo(""),
      h("h2", "Related files"),
      p(""),
      p("Review date: "),
    ],
  },

  // ---- New templates using the live-app blocks (Project Tracker / Kanban / Calendar) ----
  {
    id: "client-project-tracker",
    name: "Client Project Tracker",
    description: "Track a client's projects with owners, statuses, deadlines, and files.",
    category: "Stewardship",
    content: [
      h("h1", "Client Project Tracker"),
      p("Client: "),
      p("Advisor: "),
      h("h2", "Projects"),
      projectTracker([
        trackerRow("Stewardship Blueprint", { status: "In Progress" }),
        trackerRow("Financial plan draft", { status: "Upcoming" }),
        trackerRow("Annual review", { status: "Upcoming" }),
      ]),
      h("h2", "Notes"),
      p(""),
      h("h2", "Follow-ups"),
      todo(""),
    ],
  },
  {
    id: "six-week-challenge",
    name: "6-Week Challenge Planner",
    description: "Plan a 6-Week Challenge cohort — session calendar, weekly prep board, and checklist.",
    category: "Experiences",
    content: [
      h("h1", "6-Week Challenge Planner"),
      p("Cohort / group: "),
      p("Start date: "),
      h("h2", "Session calendar"),
      calendar(),
      h("h2", "Weekly prep"),
      kanban([
        column("To prepare", GOLD, ["Week 1 email", "Week 1 materials"]),
        column("In progress", BRONZE),
        column("Sent", DEEP_GOLD),
      ]),
      h("h2", "Facilitator checklist"),
      todo("Confirm roster"),
      todo("Schedule the six sessions"),
      todo("Send the welcome message"),
    ],
  },
  {
    id: "content-pipeline",
    name: "Content & Blog Pipeline",
    description: "Move blog and social content from idea to published, with a schedule.",
    category: "Marketing",
    content: [
      h("h1", "Content & Blog Pipeline"),
      p("Owner: "),
      h("h2", "Pipeline"),
      kanban([
        column("Ideas", GOLD, ["Blog: stewardship basics", "Social: client testimony"]),
        column("Drafting", BRONZE),
        column("Review", DEEP_GOLD),
        column("Published", INK),
      ]),
      h("h2", "Scheduled pieces"),
      projectTracker([
        trackerRow("Blog post", { status: "Upcoming" }),
        trackerRow("Newsletter", { status: "Upcoming" }),
      ]),
      h("h2", "Publishing calendar"),
      calendar(),
    ],
  },
  {
    id: "event-speaking-planner",
    name: "Event & Speaking Planner",
    description: "Plan an event or speaking engagement — key dates, task owners, and a day-of checklist.",
    category: "Marketing",
    content: [
      h("h1", "Event & Speaking Planner"),
      p("Event: "),
      p("Date & venue: "),
      h("h2", "Key dates"),
      calendar(),
      h("h2", "Tasks"),
      projectTracker([
        trackerRow("Confirm venue", { status: "In Progress" }),
        trackerRow("Promote event", { status: "Upcoming" }),
        trackerRow("Prepare the talk", { status: "Upcoming" }),
      ]),
      h("h2", "Day-of checklist"),
      todo("A/V check"),
      todo("Materials printed"),
      todo("Registration table ready"),
    ],
  },
  {
    id: "quarterly-goals",
    name: "Quarterly Goals & Initiatives",
    description: "Set quarterly goals with owners and track initiatives on a board.",
    category: "Operations",
    content: [
      h("h1", "Quarterly Goals & Initiatives"),
      p("Quarter: "),
      h("h2", "Goals"),
      projectTracker([
        trackerRow("Grow the client base", { status: "In Progress" }),
        trackerRow("Launch a new experience", { status: "Upcoming" }),
        trackerRow("Hold a steady content cadence", { status: "Upcoming" }),
      ]),
      h("h2", "Initiatives"),
      kanban([
        column("Planned", GOLD),
        column("Active", BRONZE),
        column("Done", DEEP_GOLD),
      ]),
      h("h2", "Notes"),
      p(""),
    ],
  },
  {
    id: "facilitator-cohort",
    name: "Facilitator Cohort Board",
    description: "Lead a cohort — participants by stage, a session schedule, and follow-ups.",
    category: "Experiences",
    content: [
      h("h1", "Facilitator Cohort Board"),
      p("Facilitator: "),
      p("Cohort: "),
      h("h2", "Participants by stage"),
      kanban([
        column("Invited", GOLD),
        column("Active", BRONZE),
        column("Completed", DEEP_GOLD),
      ]),
      h("h2", "Session schedule"),
      calendar(),
      h("h2", "Follow-ups"),
      projectTracker([
        trackerRow("Weekly check-in", { status: "Upcoming" }),
      ]),
    ],
  },
];

export function getTemplateContent(id: string): Node[] | null {
  return WORKSPACE_TEMPLATES.find((t) => t.id === id)?.content ?? null;
}
