// The dashboard entity + field registry that gives Bolt a firm understanding of
// every dashboard object and its fields. Generic CRUD tools operate through this.
import type { AgentEntity } from "./types";

const A = ["super_admin", "admin"];
const OPS = ["super_admin", "admin", "project_manager", "estimator"];
const PM = ["super_admin", "admin", "project_manager"];
const CONTENT = ["super_admin", "admin", "designer"];

export const ENTITIES: AgentEntity[] = [
  {
    key: "contact", label: "Contact", plural: "contacts", table: "contacts",
    description: "People & companies in the CRM — clients, leads, vendors, subcontractors.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["first_name", "last_name", "email", "company"],
    orderBy: { column: "last_activity", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "first_name", type: "string", desc: "First name", required: true },
      { name: "last_name", type: "string", desc: "Last name", required: true },
      { name: "email", type: "string", desc: "Email address", required: true },
      { name: "phone", type: "string", desc: "Phone number" },
      { name: "company", type: "string", desc: "Company name" },
      { name: "type", type: "enum", desc: "Contact type", enumValues: ["Client", "Lead", "Prospect", "Customer", "Vendor", "Sub Contractor", "Designer", "Other"] },
      { name: "status", type: "enum", desc: "Lifecycle status", enumValues: ["active", "inactive", "archived"] },
      { name: "address", type: "string", desc: "Street address" },
      { name: "city", type: "string", desc: "City" },
      { name: "state", type: "string", desc: "State" },
      { name: "zip", type: "string", desc: "ZIP / postal code" },
      { name: "notes", type: "text", desc: "Internal notes" },
      { name: "tags", type: "string[]", desc: "Tags" },
      { name: "source", type: "string", desc: "Lead/contact source" },
    ],
  },
  {
    key: "quote", label: "Quote / Lead", plural: "quotes", table: "quotes",
    description: "Estimate requests and sales leads.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["name", "email", "project_type"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "name", type: "string", desc: "Lead / requester name", required: true },
      { name: "email", type: "string", desc: "Email" },
      { name: "phone", type: "string", desc: "Phone" },
      { name: "contact_id", type: "string", desc: "Linked contact id (uuid)" },
      { name: "project_type", type: "string", desc: "Type of project requested" },
      { name: "location", type: "string", desc: "Project location" },
      { name: "sq_ft", type: "string", desc: "Square footage" },
      { name: "budget_range", type: "string", desc: "Budget range" },
      { name: "timeline", type: "string", desc: "Desired timeline" },
      { name: "services", type: "string[]", desc: "Requested services" },
      { name: "description", type: "text", desc: "Project description" },
      { name: "status", type: "enum", desc: "Pipeline stage", enumValues: ["New", "In Review", "Quoted", "Won", "Lost"] },
      { name: "estimated_value", type: "number", desc: "Estimated $ value" },
      { name: "source", type: "string", desc: "Lead source" },
    ],
  },
  {
    key: "opportunity", label: "Sales Opportunity", plural: "opportunities", table: "pipeline_opportunities",
    description: "Sales pipeline records — a realistic project tracked from Opportunity through Closed. A job number is auto-assigned on create (never set it yourself). Stage transitions must follow the allowed path (opportunity→active_budget→pre_construction_design→active_project→warranty→closed, with long_lead / not_moving_forward alternates); prefer prompting staff and using the pipeline transition flow rather than force-setting `stage`. Do not mark active_project without construction agreement + start date + PM, and never treat a plain CRM contact as an opportunity unless a real project exists.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["opportunity_name", "job_number", "project_address", "assigned_owner"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "opportunity_name", type: "string", desc: "Opportunity / project name", required: true },
      { name: "stage", type: "enum", desc: "Lifecycle stage", enumValues: ["opportunity", "active_budget", "pre_construction_design", "active_project", "warranty", "closed", "long_lead", "not_moving_forward"] },
      { name: "job_number", type: "string", desc: "Auto-assigned (CM-YYYY-####). Do not set.", readonly: true },
      { name: "contact_id", type: "string", desc: "Linked contact id" },
      { name: "linked_quote_id", type: "string", desc: "Source quote id, if converted from a quote" },
      { name: "project_type", type: "enum", desc: "Project type", enumValues: ["remodel", "addition", "adu", "casita", "custom_home", "commercial", "interior_renovation", "exterior_renovation", "other"] },
      { name: "project_address", type: "string", desc: "Project address" },
      { name: "city", type: "string", desc: "City" },
      { name: "state", type: "string", desc: "State" },
      { name: "zip_code", type: "string", desc: "ZIP" },
      { name: "estimated_budget_range", type: "string", desc: "Budget range" },
      { name: "estimated_project_value", type: "number", desc: "Estimated $ value" },
      { name: "probability_percent", type: "number", desc: "Win probability 0-100" },
      { name: "source", type: "string", desc: "Source" },
      { name: "referral_source", type: "string", desc: "Referral source" },
      { name: "assigned_owner", type: "string", desc: "Assigned owner (name)" },
      { name: "tags", type: "string[]", desc: "Tags" },
      { name: "notes", type: "text", desc: "Scope / notes" },
      { name: "budget_status", type: "string", desc: "Active-budget sub-status" },
      { name: "current_budget_total", type: "number", desc: "Current budget total" },
      { name: "projected_construction_value", type: "number", desc: "Forecast construction value (pre-con)" },
      { name: "contract_value", type: "number", desc: "Executed contract value (active project)" },
      { name: "start_date", type: "date", desc: "Construction start date" },
      { name: "actual_completion_date", type: "date", desc: "Actual completion date" },
      { name: "warranty_start_date", type: "date", desc: "Warranty start date" },
      { name: "warranty_expiration_date", type: "date", desc: "Warranty expiration date" },
      { name: "closed_date", type: "date", desc: "Closed/archived date" },
      { name: "long_lead_reason", type: "enum", desc: "Long-lead reason", enumValues: ["waiting_on_financing", "waiting_on_design", "future_purchase", "planning_for_next_year", "timing_not_right", "client_not_ready", "other"] },
      { name: "follow_up_date", type: "date", desc: "Long-lead follow-up date" },
      { name: "follow_up_owner", type: "string", desc: "Long-lead follow-up owner" },
      { name: "lost_reason", type: "enum", desc: "Not-moving-forward reason", enumValues: ["not_feasible", "outside_budget", "chose_another_builder", "cancelled", "on_hold_indefinitely", "client_unresponsive", "scope_not_aligned", "timeline_not_aligned", "not_ideal_project_type", "duplicate", "other"] },
      { name: "project_manager", type: "string", desc: "Project manager" },
    ],
  },
  {
    key: "job", label: "Job", plural: "jobs", table: "jobs",
    description: "The central construction project record (created when an Opportunity becomes a real project). Job number (YY_###_Name) is auto-assigned on create — never set it yourself. Links to the sales pipeline via related_opportunity_id. Use the Jobs pages to promote opportunities, manage clients/vendors/internal users, settings, and insurance; follow the status list and don't fabricate contract/dates.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["job_name", "job_number", "full_address", "city"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: PM,
    fields: [
      { name: "job_name", type: "string", desc: "Unique job name", required: true },
      { name: "job_number", type: "string", desc: "Auto-assigned YY_###_Name. Do not set.", readonly: true },
      { name: "status", type: "enum", desc: "Job status", enumValues: ["draft", "opportunity", "active_budget", "pre_construction_design", "active_project", "warranty", "closed", "long_lead", "not_moving_forward", "on_hold", "cancelled"] },
      { name: "job_type_id", type: "string", desc: "Job type id" },
      { name: "job_group_id", type: "string", desc: "Job group id" },
      { name: "related_opportunity_id", type: "string", desc: "Source opportunity id" },
      { name: "contract_type", type: "enum", desc: "Contract type", enumValues: ["fixed_price", "open_book"] },
      { name: "contract_price", type: "number", desc: "Contract price" },
      { name: "street_address", type: "string", desc: "Street" },
      { name: "city", type: "string", desc: "City" },
      { name: "state", type: "string", desc: "State" },
      { name: "zip_code", type: "string", desc: "ZIP" },
      { name: "projected_start_date", type: "date", desc: "Projected start" },
      { name: "projected_completion_date", type: "date", desc: "Projected completion" },
      { name: "actual_start_date", type: "date", desc: "Actual start" },
      { name: "actual_completion_date", type: "date", desc: "Actual completion" },
      { name: "project_manager", type: "string", desc: "PM name (see job_internal_users for assignments)" },
      { name: "square_feet", type: "number", desc: "Square feet" },
      { name: "permit_number", type: "string", desc: "Permit number" },
      { name: "is_template", type: "boolean", desc: "Whether this job is a template" },
      { name: "internal_notes", type: "text", desc: "Internal notes" },
      { name: "vendor_notes", type: "text", desc: "Notes for subs/vendors" },
    ],
  },
  {
    key: "change_order", label: "Change Order", plural: "change orders", table: "change_orders",
    description: "Job change orders. co_number is auto-assigned per job; approved change orders roll into the Job Price Summary. Don't fabricate amounts or approvals.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["co_number", "title"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: PM,
    fields: [
      { name: "job_id", type: "string", desc: "Parent job id", required: true },
      { name: "co_number", type: "string", desc: "Auto CO-#### (do not set)", readonly: true },
      { name: "title", type: "string", desc: "Title", required: true },
      { name: "description", type: "text", desc: "Scope of change" },
      { name: "status", type: "enum", desc: "Status", enumValues: ["draft", "submitted", "pending_approval", "approved", "rejected", "void"] },
      { name: "amount", type: "number", desc: "Change amount ($)" },
      { name: "co_date", type: "date", desc: "Change order date" },
      { name: "requested_by", type: "string", desc: "Requested by" },
      { name: "client_visible", type: "boolean", desc: "Visible to client" },
    ],
  },
  {
    key: "invoice", label: "Invoice", plural: "invoices", table: "invoices",
    description: "Job invoices (with line items in invoice_line_items). invoice_number is auto-assigned per job. Balance = amount - amount_paid. PDFs/emails are generated by the Invoices UI, not by writing rows. Don't fabricate amounts or payments.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["invoice_number", "title"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: PM,
    fields: [
      { name: "job_id", type: "string", desc: "Parent job id", required: true },
      { name: "invoice_number", type: "string", desc: "Auto INV-#### (do not set)", readonly: true },
      { name: "title", type: "string", desc: "Title" },
      { name: "status", type: "enum", desc: "Status", enumValues: ["draft", "sent", "partial", "paid", "overdue", "void"] },
      { name: "issue_date", type: "date", desc: "Issue date" },
      { name: "due_date", type: "date", desc: "Due date" },
      { name: "amount", type: "number", desc: "Total (from line items)" },
      { name: "amount_paid", type: "number", desc: "Amount paid" },
      { name: "notes", type: "text", desc: "Notes" },
      { name: "client_visible", type: "boolean", desc: "Visible to client" },
    ],
  },
  {
    key: "daily_log", label: "Daily Log", plural: "daily logs", table: "daily_logs",
    description: "Job daily logs (field notes, weather, crew, hours, delays).",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["title", "notes"],
    orderBy: { column: "log_date", ascending: false }, writeRoles: ["super_admin", "admin", "project_manager", "superintendent"],
    fields: [
      { name: "job_id", type: "string", desc: "Parent job id", required: true },
      { name: "log_date", type: "date", desc: "Log date", required: true },
      { name: "title", type: "string", desc: "Title" },
      { name: "notes", type: "text", desc: "Notes" },
      { name: "weather", type: "string", desc: "Weather" },
      { name: "temperature", type: "string", desc: "Temperature" },
      { name: "hours_worked", type: "number", desc: "Hours worked" },
      { name: "crew", type: "string[]", desc: "Crew" },
      { name: "visitors", type: "string", desc: "Visitors" },
      { name: "delays", type: "text", desc: "Delays / issues" },
      { name: "client_visible", type: "boolean", desc: "Visible to client" },
    ],
  },
  {
    key: "job_file", label: "Job File", plural: "job files", table: "job_files",
    description: "Files attached to a job (stored in the cmi-media bucket). Uploads happen via the Files UI; you can read/list/relabel/delete records.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["name", "folder"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: ["super_admin", "admin", "project_manager", "superintendent"],
    fields: [
      { name: "job_id", type: "string", desc: "Parent job id", required: true },
      { name: "name", type: "string", desc: "File name", required: true },
      { name: "file_url", type: "string", desc: "Public URL", required: true },
      { name: "folder", type: "string", desc: "Folder" },
      { name: "category", type: "string", desc: "Category" },
      { name: "client_visible", type: "boolean", desc: "Visible to client" },
    ],
  },
  {
    key: "warranty_request", label: "Warranty Request", plural: "warranty requests", table: "warranty_requests",
    description: "Client-submitted warranty issues tied back to a project (job number / opportunity).",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["request_title", "job_number", "submitted_by"],
    orderBy: { column: "submitted_at", ascending: false }, writeRoles: ["super_admin", "admin", "project_manager", "superintendent"],
    fields: [
      { name: "request_title", type: "string", desc: "Short title", required: true },
      { name: "request_description", type: "text", desc: "Description of the issue" },
      { name: "opportunity_id", type: "string", desc: "Linked opportunity/project id" },
      { name: "job_number", type: "string", desc: "Project job number" },
      { name: "contact_id", type: "string", desc: "Linked contact id" },
      { name: "location_in_home", type: "string", desc: "Location in home" },
      { name: "priority", type: "enum", desc: "Priority", enumValues: ["low", "normal", "urgent"] },
      { name: "status", type: "enum", desc: "Status", enumValues: ["submitted", "under_review", "scheduled", "in_progress", "resolved", "closed"] },
      { name: "assigned_to", type: "string", desc: "Assigned staff" },
    ],
  },
  {
    key: "project_item", label: "Project / Task", plural: "project items", table: "project_schedule_items",
    description: "Project schedule items — projects, phases, tasks, and milestones on the Gantt/PM board.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["title", "project_title", "assignee", "client"],
    orderBy: { column: "start_date", ascending: true }, writeRoles: PM,
    fields: [
      { name: "type", type: "enum", desc: "Item type", required: true, enumValues: ["project", "phase", "task", "milestone"] },
      { name: "title", type: "string", desc: "Item title", required: true },
      { name: "project_title", type: "string", desc: "Parent project title" },
      { name: "phase", type: "string", desc: "Phase name" },
      { name: "assignee", type: "string", desc: "Assigned person" },
      { name: "client", type: "string", desc: "Client name" },
      { name: "start_date", type: "date", desc: "Start date (YYYY-MM-DD)", required: true },
      { name: "end_date", type: "date", desc: "End date (YYYY-MM-DD)", required: true },
      { name: "status", type: "enum", desc: "Status", enumValues: ["pending", "scheduled", "in_progress", "waiting", "delayed", "blocked", "needs_approval", "complete", "canceled"] },
      { name: "priority", type: "enum", desc: "Priority", enumValues: ["low", "normal", "high", "urgent", "critical", "blocking_closeout"] },
      { name: "progress", type: "number", desc: "Percent complete 0-100" },
      { name: "description", type: "text", desc: "Description" },
      { name: "internal_notes", type: "text", desc: "Internal notes" },
      { name: "blocker_reason", type: "text", desc: "Why blocked, if blocked" },
      { name: "client_visible", type: "boolean", desc: "Visible to client" },
      { name: "board_id", type: "string", desc: "Board id (default 'default')" },
      { name: "project_id", type: "string", desc: "Linked project id" },
      { name: "sort_order", type: "number", desc: "Sort order" },
      { name: "duration_minutes", type: "number", desc: "Duration in minutes" },
    ],
  },
  {
    key: "document", label: "Document (Contract / SOW)", plural: "documents", table: "documents",
    description: "Contracts, scopes of work, and proposals generated for clients.",
    idColumn: "id", customIdPrefix: "DOC-", hasUpdatedAt: true, searchColumns: ["title", "client", "project"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "title", type: "string", desc: "Document title", required: true },
      { name: "type", type: "enum", desc: "Document type", enumValues: ["contract", "sow", "proposal", "change_order", "other"] },
      { name: "status", type: "string", desc: "Status (e.g. draft, sent, signed)" },
      { name: "client", type: "string", desc: "Client name" },
      { name: "client_email", type: "string", desc: "Client email" },
      { name: "client_phone", type: "string", desc: "Client phone" },
      { name: "project", type: "string", desc: "Project name" },
      { name: "location", type: "string", desc: "Project location" },
      { name: "value", type: "string", desc: "Contract value" },
      { name: "deposit", type: "string", desc: "Deposit amount" },
      { name: "payment_schedule", type: "text", desc: "Payment schedule" },
      { name: "payment_terms", type: "text", desc: "Payment terms" },
      { name: "allowances", type: "text", desc: "Allowances" },
      { name: "sq_ft", type: "string", desc: "Square footage" },
      { name: "services", type: "text", desc: "Services covered" },
      { name: "description", type: "text", desc: "Scope description" },
      { name: "deliverables", type: "text", desc: "Deliverables" },
      { name: "exclusions", type: "text", desc: "Exclusions" },
      { name: "assumptions", type: "text", desc: "Assumptions" },
      { name: "warranty", type: "text", desc: "Warranty terms" },
      { name: "start_date", type: "string", desc: "Start date" },
      { name: "completion_date", type: "string", desc: "Completion date" },
      { name: "prepared_by", type: "string", desc: "Prepared by" },
      { name: "cmi_rep", type: "string", desc: "CMI representative" },
      { name: "notes", type: "text", desc: "Notes" },
    ],
  },
  {
    key: "blog_post", label: "Blog Post", plural: "blog posts", table: "blog_posts",
    description: "Blog/news articles (also sync to WordPress).",
    idColumn: "id", slugFrom: "title", hasUpdatedAt: true, searchColumns: ["title", "category"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: CONTENT,
    fields: [
      { name: "title", type: "string", desc: "Post title", required: true },
      { name: "slug", type: "string", desc: "URL slug (auto from title if blank)" },
      { name: "category", type: "string", desc: "Category" },
      { name: "excerpt", type: "text", desc: "Short excerpt" },
      { name: "content", type: "text", desc: "Body content (HTML/markdown)" },
      { name: "featured_image", type: "string", desc: "Featured image URL" },
      { name: "tags", type: "string[]", desc: "Tags" },
      { name: "author", type: "string", desc: "Author name" },
      { name: "status", type: "enum", desc: "Publish status", enumValues: ["draft", "published", "scheduled", "archived"] },
      { name: "published_at", type: "date", desc: "Publish date" },
    ],
  },
  {
    key: "email_template", label: "Email Template", plural: "email templates", table: "email_templates",
    description: "Reusable email templates for the communications composer.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["name", "subject"],
    orderBy: { column: "updated_at", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "name", type: "string", desc: "Template name", required: true },
      { name: "subject", type: "string", desc: "Email subject" },
      { name: "preview_text", type: "string", desc: "Inbox preview text" },
      { name: "builder_type", type: "enum", desc: "How it's built", enumValues: ["visual", "html"] },
      { name: "html", type: "text", desc: "Rendered HTML body" },
      { name: "trigger_event", type: "string", desc: "Automation trigger, if any" },
      { name: "status", type: "string", desc: "Status (active/draft)" },
    ],
  },
  {
    key: "portfolio_item", label: "Portfolio Item", plural: "portfolio items", table: "portfolio",
    description: "Public portfolio/showcase projects.",
    idColumn: "id", slugFrom: "title", hasUpdatedAt: true, searchColumns: ["title", "category", "location"],
    orderBy: { column: "sort_order", ascending: true }, writeRoles: CONTENT,
    fields: [
      { name: "title", type: "string", desc: "Project title", required: true },
      { name: "slug", type: "string", desc: "URL slug" },
      { name: "subtitle", type: "string", desc: "Subtitle" },
      { name: "category", type: "string", desc: "Category" },
      { name: "location", type: "string", desc: "Location" },
      { name: "timeline", type: "string", desc: "Timeline" },
      { name: "year", type: "number", desc: "Year completed" },
      { name: "square_feet", type: "number", desc: "Square footage" },
      { name: "description", type: "text", desc: "Description" },
      { name: "featured_image", type: "string", desc: "Featured image URL" },
      { name: "services_used", type: "string[]", desc: "Services used" },
      { name: "tags", type: "string[]", desc: "Tags" },
      { name: "status", type: "enum", desc: "Status", enumValues: ["draft", "published", "hidden", "archived"] },
      { name: "is_featured", type: "boolean", desc: "Featured on site" },
      { name: "client_visible", type: "boolean", desc: "Visible to clients" },
    ],
  },
  {
    key: "team_member", label: "Team Member", plural: "team members", table: "team_members",
    description: "Public team/staff directory profiles.",
    idColumn: "id", slugFrom: "name", hasUpdatedAt: true, searchColumns: ["name", "role", "department"],
    orderBy: { column: "sort_order", ascending: true }, writeRoles: A,
    fields: [
      { name: "name", type: "string", desc: "Full name", required: true },
      { name: "role", type: "string", desc: "Job role/title" },
      { name: "department", type: "string", desc: "Department" },
      { name: "bio", type: "text", desc: "Biography" },
      { name: "tagline", type: "string", desc: "Short tagline" },
      { name: "email", type: "string", desc: "Email" },
      { name: "phone", type: "string", desc: "Phone" },
      { name: "profile_photo", type: "string", desc: "Photo URL" },
      { name: "attributes", type: "string[]", desc: "Attribute tags" },
      { name: "availability", type: "string", desc: "Availability note" },
      { name: "sort_order", type: "number", desc: "Sort order" },
      { name: "status", type: "enum", desc: "Status", enumValues: ["active", "inactive"] },
    ],
  },
  {
    key: "selection", label: "Project Selection", plural: "selections", table: "project_selections",
    description: "Client material/product selections for projects.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["name", "project_name", "category"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "name", type: "string", desc: "Selection name", required: true },
      { name: "project_id", type: "string", desc: "Project id" },
      { name: "project_name", type: "string", desc: "Project name" },
      { name: "room_area_name", type: "string", desc: "Room/area" },
      { name: "category", type: "string", desc: "Category" },
      { name: "custom_product_name", type: "string", desc: "Custom product name" },
      { name: "description", type: "text", desc: "Description" },
      { name: "selection_status", type: "string", desc: "Selection status" },
      { name: "approval_status", type: "string", desc: "Approval status" },
      { name: "procurement_status", type: "string", desc: "Procurement status" },
      { name: "install_status", type: "string", desc: "Install status" },
      { name: "quantity", type: "number", desc: "Quantity" },
      { name: "estimated_cost", type: "number", desc: "Estimated cost" },
      { name: "client_price", type: "number", desc: "Client price" },
      { name: "client_visible", type: "boolean", desc: "Visible to client" },
      { name: "internal_notes", type: "text", desc: "Internal notes" },
    ],
  },
  {
    key: "product", label: "Product", plural: "products", table: "products",
    description: "Product catalog used for selections.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["product_name", "brand", "sku"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "product_name", type: "string", desc: "Product name", required: true },
      { name: "category", type: "string", desc: "Category" },
      { name: "brand", type: "string", desc: "Brand" },
      { name: "manufacturer", type: "string", desc: "Manufacturer" },
      { name: "sku", type: "string", desc: "SKU" },
      { name: "model_number", type: "string", desc: "Model number" },
      { name: "description", type: "text", desc: "Description" },
      { name: "unit_cost", type: "number", desc: "Unit cost" },
      { name: "retail_price", type: "number", desc: "Retail price" },
      { name: "availability_status", type: "enum", desc: "Availability", enumValues: ["available", "limited", "out_of_stock", "discontinued", "special_order", "unknown"] },
      { name: "lead_time_days", type: "number", desc: "Lead time (days)" },
      { name: "product_url", type: "string", desc: "Product URL" },
      { name: "image_url", type: "string", desc: "Image URL" },
    ],
  },
  {
    key: "booking", label: "Booking / Appointment", plural: "bookings", table: "booking_appointments",
    description: "Scheduled appointments and consultations.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["title", "customer_email", "customer_first_name", "customer_last_name"],
    orderBy: { column: "start_time", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "title", type: "string", desc: "Appointment title" },
      { name: "customer_first_name", type: "string", desc: "Customer first name" },
      { name: "customer_last_name", type: "string", desc: "Customer last name" },
      { name: "customer_email", type: "string", desc: "Customer email" },
      { name: "customer_phone", type: "string", desc: "Customer phone" },
      { name: "start_time", type: "date", desc: "Start time (ISO)", required: true },
      { name: "end_time", type: "date", desc: "End time (ISO)" },
      { name: "status", type: "enum", desc: "Status", enumValues: ["pending", "confirmed", "rescheduled", "canceled", "completed", "no_show"] },
      { name: "location_type", type: "string", desc: "Location type" },
      { name: "meeting_url", type: "string", desc: "Meeting URL" },
      { name: "customer_notes", type: "text", desc: "Customer notes" },
      { name: "internal_notes", type: "text", desc: "Internal notes" },
      { name: "client_visible", type: "boolean", desc: "Visible to client" },
    ],
  },
  {
    key: "business_card", label: "Business Card", plural: "business cards", table: "business_cards",
    description: "Digital business cards (scalar fields; use the builder for sections/links).",
    idColumn: "id", slugFrom: "card_name", hasUpdatedAt: true, searchColumns: ["card_name", "display_name", "slug"],
    orderBy: { column: "updated_at", ascending: false }, writeRoles: A,
    fields: [
      { name: "card_name", type: "string", desc: "Internal card name", required: true },
      { name: "slug", type: "string", desc: "Public slug" },
      { name: "status", type: "enum", desc: "Status", enumValues: ["draft", "published", "unpublished", "archived"] },
      { name: "staff_user_id", type: "string", desc: "Owner staff user id" },
      { name: "display_name", type: "string", desc: "Display name" },
      { name: "job_title", type: "string", desc: "Job title" },
      { name: "company_name", type: "string", desc: "Company" },
      { name: "bio", type: "text", desc: "Bio" },
      { name: "primary_phone", type: "string", desc: "Phone" },
      { name: "primary_email", type: "string", desc: "Email" },
      { name: "website_url", type: "string", desc: "Website" },
      { name: "nfc_status", type: "string", desc: "NFC status" },
    ],
  },
  {
    key: "contact_submission", label: "Contact Form Submission", plural: "contact submissions", table: "contact_submissions",
    description: "Inbound contact-form submissions from the public website.",
    idColumn: "id", searchColumns: ["first_name", "last_name", "email", "subject"],
    orderBy: { column: "submitted_at", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "first_name", type: "string", desc: "First name" },
      { name: "last_name", type: "string", desc: "Last name" },
      { name: "email", type: "string", desc: "Email" },
      { name: "phone", type: "string", desc: "Phone" },
      { name: "subject", type: "string", desc: "Subject" },
      { name: "message", type: "text", desc: "Message" },
      { name: "status", type: "enum", desc: "Status", enumValues: ["new", "read", "archived"] },
    ],
  },
  {
    key: "message", label: "Message Log", plural: "messages", table: "messages",
    description: "Logged emails, SMS, and calls. To SEND email/SMS use the send_message tool, not create.",
    idColumn: "id", searchColumns: ["to_address", "from_address", "subject"],
    orderBy: { column: "sent_at", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "direction", type: "enum", desc: "Direction", enumValues: ["outbound", "inbound"] },
      { name: "channel", type: "enum", desc: "Channel", enumValues: ["email", "sms", "call"] },
      { name: "to_address", type: "string", desc: "Recipient" },
      { name: "from_address", type: "string", desc: "Sender" },
      { name: "subject", type: "string", desc: "Subject (email)" },
      { name: "body", type: "text", desc: "Message body" },
      { name: "status", type: "string", desc: "Delivery status" },
      { name: "contact_id", type: "string", desc: "Linked contact id" },
    ],
  },
  {
    key: "meeting", label: "Meeting", plural: "meetings", table: "meetings",
    description: "Recorded & transcribed meetings with AI summaries and action items (Recording Studio).",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["title", "summary", "location"],
    orderBy: { column: "meeting_date", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "title", type: "string", desc: "Meeting title", required: true },
      { name: "meeting_type", type: "string", desc: "Type (client_meeting, site_walkthrough, internal_staff, etc.)" },
      { name: "status", type: "enum", desc: "Status", enumValues: ["draft", "processing", "transcribed", "reviewed", "action_items_created", "shared_with_client", "archived"] },
      { name: "meeting_date", type: "date", desc: "Date/time (ISO)" },
      { name: "duration_seconds", type: "number", desc: "Duration in seconds" },
      { name: "location", type: "string", desc: "Location or platform" },
      { name: "contact_id", type: "string", desc: "Related contact id" },
      { name: "project_item_id", type: "string", desc: "Related project id" },
      { name: "quote_id", type: "string", desc: "Related quote id" },
      { name: "staff_user_id", type: "string", desc: "Related/assigned staff id" },
      { name: "summary", type: "text", desc: "AI summary" },
      { name: "transcript", type: "text", desc: "Full transcript" },
      { name: "follow_up_notes", type: "text", desc: "Follow-up notes" },
      { name: "internal_notes", type: "text", desc: "Internal notes" },
      { name: "client_notes", type: "text", desc: "Client-facing notes" },
      { name: "client_visible", type: "boolean", desc: "Client-facing summary approved" },
    ],
  },
  {
    key: "user", label: "Staff User", plural: "staff users", table: "staff_users",
    description: "Staff accounts and roles. Sensitive — admin only.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["email", "display_name", "first_name", "last_name"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: A, deleteRoles: ["super_admin"],
    fields: [
      { name: "email", type: "string", desc: "Email", required: true },
      { name: "first_name", type: "string", desc: "First name", required: true },
      { name: "last_name", type: "string", desc: "Last name", required: true },
      { name: "display_name", type: "string", desc: "Display name" },
      { name: "phone", type: "string", desc: "Phone" },
      { name: "role_slug", type: "enum", desc: "Role", enumValues: ["super_admin", "admin", "project_manager", "staff", "designer", "estimator", "superintendent", "subcontractor", "vendor", "client", "viewer"] },
      { name: "status", type: "enum", desc: "Account status", enumValues: ["active", "invited", "pending", "disabled", "removed", "suspended", "archived"] },
      { name: "title", type: "string", desc: "Title" },
      { name: "company_name", type: "string", desc: "Company" },
      { name: "job_title", type: "string", desc: "Job title" },
      { name: "notes", type: "text", desc: "Notes" },
    ],
  },
  {
    key: "page_review_note", label: "Page Review Note", plural: "page review notes", table: "page_review_notes",
    description: "Super Admin Live Page Editor review notes attached to page elements. READ these to understand requested changes. Any change you propose must be a DRAFT (set status='draft', ai_generated=true) — never publish.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["note", "change_type"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: ["super_admin"], deleteRoles: ["super_admin"],
    fields: [
      { name: "review_session_id", type: "string", desc: "Parent review session id", required: true },
      { name: "element_id", type: "string", desc: "Reviewed element id" },
      { name: "note", type: "text", desc: "Requested change / note", required: true },
      { name: "priority", type: "enum", desc: "Priority", enumValues: ["low", "medium", "high", "urgent"] },
      { name: "status", type: "enum", desc: "Status (AI proposals must be 'draft')", enumValues: ["draft", "open", "in_progress", "resolved", "archived"] },
      { name: "change_type", type: "string", desc: "Change type (copy_update, styling_update, new_section, ai_rewrite_request, etc.)" },
      { name: "insert_kind", type: "string", desc: "For 'addition' requests: section | row | column | card | component" },
      { name: "component_name", type: "string", desc: "For component additions: the ShadCN component to base it on (e.g. Card, Tabs, Hero block)" },
      { name: "ai_generated", type: "boolean", desc: "True when Bolt drafted this note" },
    ],
  },
  {
    key: "page_review_export", label: "Page Review Export", plural: "page review exports", table: "page_review_exports",
    description: "AI-readable export briefs from the Live Page Editor. Read export_payload for the structured page-review brief. Read-only for Bolt.",
    idColumn: "id", searchColumns: ["file_type"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: ["super_admin"], deleteRoles: ["super_admin"],
    fields: [
      { name: "review_session_id", type: "string", desc: "Parent review session id" },
      { name: "file_type", type: "string", desc: "Export type (markdown, ai_brief)" },
      { name: "ai_visible", type: "boolean", desc: "Flagged for AI consumption" },
    ],
  },
];

export function getEntity(key: string): AgentEntity | undefined {
  return ENTITIES.find((e) => e.key === key || e.plural === key || e.table === key);
}

export function entityOverview(): string {
  return ENTITIES.map((e) => `- ${e.key}: ${e.description}`).join("\n");
}
