// The dashboard entity + field registry that gives Bolt a firm understanding of
// every dashboard object and its fields. Generic CRUD tools operate through this.
import type { AgentEntity } from "./types";

const A = ["super_admin", "admin"];
const OPS = ["super_admin", "admin", "project_manager", "estimator"];
const PM = ["super_admin", "admin", "project_manager"];
const CONTENT = ["super_admin", "admin", "designer"];

export const ENTITIES: AgentEntity[] = [
  {
    key: "contact", label: "Contact", plural: "contacts", table: "contacts",
    description: "People & companies in the CRM — clients, leads, vendors, subcontractors.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["first_name", "last_name", "email", "company"],
    orderBy: { column: "last_activity", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "first_name", type: "string", desc: "First name", required: true },
      { name: "last_name", type: "string", desc: "Last name", required: true },
      { name: "email", type: "string", desc: "Email address", required: true },
      { name: "phone", type: "string", desc: "Phone number" },
      { name: "company", type: "string", desc: "Company name" },
      { name: "type", type: "enum", desc: "Contact type", enumValues: ["Client", "Lead", "Vendor", "Sub Contractor"] },
      { name: "status", type: "enum", desc: "Lifecycle status", enumValues: ["active", "inactive", "archived"] },
      { name: "address", type: "string", desc: "Street address" },
      { name: "city", type: "string", desc: "City" },
      { name: "state", type: "string", desc: "State" },
      { name: "zip", type: "string", desc: "ZIP / postal code" },
      { name: "notes", type: "text", desc: "Internal notes" },
      { name: "tags", type: "string[]", desc: "Tags" },
      { name: "source", type: "string", desc: "Lead/contact source" },
    ],
  },
  {
    key: "quote", label: "Quote / Lead", plural: "quotes", table: "quotes",
    description: "Estimate requests and sales leads.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["name", "email", "project_type"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "name", type: "string", desc: "Lead / requester name", required: true },
      { name: "email", type: "string", desc: "Email" },
      { name: "phone", type: "string", desc: "Phone" },
      { name: "contact_id", type: "string", desc: "Linked contact id (uuid)" },
      { name: "project_type", type: "string", desc: "Type of project requested" },
      { name: "location", type: "string", desc: "Project location" },
      { name: "sq_ft", type: "string", desc: "Square footage" },
      { name: "budget_range", type: "string", desc: "Budget range" },
      { name: "timeline", type: "string", desc: "Desired timeline" },
      { name: "services", type: "string[]", desc: "Requested services" },
      { name: "description", type: "text", desc: "Project description" },
      { name: "status", type: "enum", desc: "Pipeline stage", enumValues: ["New", "In Review", "Quoted", "Won", "Lost"] },
      { name: "estimated_value", type: "number", desc: "Estimated $ value" },
      { name: "source", type: "string", desc: "Lead source" },
    ],
  },
  {
    key: "project_item", label: "Project / Task", plural: "project items", table: "project_schedule_items",
    description: "Project schedule items — projects, phases, tasks, and milestones on the Gantt/PM board.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["title", "project_title", "assignee", "client"],
    orderBy: { column: "start_date", ascending: true }, writeRoles: PM,
    fields: [
      { name: "type", type: "enum", desc: "Item type", required: true, enumValues: ["project", "phase", "task", "milestone"] },
      { name: "title", type: "string", desc: "Item title", required: true },
      { name: "project_title", type: "string", desc: "Parent project title" },
      { name: "phase", type: "string", desc: "Phase name" },
      { name: "assignee", type: "string", desc: "Assigned person" },
      { name: "client", type: "string", desc: "Client name" },
      { name: "start_date", type: "date", desc: "Start date (YYYY-MM-DD)", required: true },
      { name: "end_date", type: "date", desc: "End date (YYYY-MM-DD)", required: true },
      { name: "status", type: "enum", desc: "Status", enumValues: ["pending", "scheduled", "in_progress", "waiting", "delayed", "blocked", "needs_approval", "complete", "canceled"] },
      { name: "priority", type: "enum", desc: "Priority", enumValues: ["low", "normal", "high", "urgent", "critical", "blocking_closeout"] },
      { name: "progress", type: "number", desc: "Percent complete 0-100" },
      { name: "description", type: "text", desc: "Description" },
      { name: "internal_notes", type: "text", desc: "Internal notes" },
      { name: "blocker_reason", type: "text", desc: "Why blocked, if blocked" },
      { name: "client_visible", type: "boolean", desc: "Visible to client" },
      { name: "board_id", type: "string", desc: "Board id (default 'default')" },
      { name: "project_id", type: "string", desc: "Linked project id" },
      { name: "sort_order", type: "number", desc: "Sort order" },
      { name: "duration_minutes", type: "number", desc: "Duration in minutes" },
    ],
  },
  {
    key: "document", label: "Document (Contract / SOW)", plural: "documents", table: "documents",
    description: "Contracts, scopes of work, and proposals generated for clients.",
    idColumn: "id", customIdPrefix: "DOC-", hasUpdatedAt: true, searchColumns: ["title", "client", "project"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "title", type: "string", desc: "Document title", required: true },
      { name: "type", type: "enum", desc: "Document type", enumValues: ["contract", "sow", "proposal", "change_order", "other"] },
      { name: "status", type: "string", desc: "Status (e.g. draft, sent, signed)" },
      { name: "client", type: "string", desc: "Client name" },
      { name: "client_email", type: "string", desc: "Client email" },
      { name: "client_phone", type: "string", desc: "Client phone" },
      { name: "project", type: "string", desc: "Project name" },
      { name: "location", type: "string", desc: "Project location" },
      { name: "value", type: "string", desc: "Contract value" },
      { name: "deposit", type: "string", desc: "Deposit amount" },
      { name: "payment_schedule", type: "text", desc: "Payment schedule" },
      { name: "payment_terms", type: "text", desc: "Payment terms" },
      { name: "allowances", type: "text", desc: "Allowances" },
      { name: "sq_ft", type: "string", desc: "Square footage" },
      { name: "services", type: "text", desc: "Services covered" },
      { name: "description", type: "text", desc: "Scope description" },
      { name: "deliverables", type: "text", desc: "Deliverables" },
      { name: "exclusions", type: "text", desc: "Exclusions" },
      { name: "assumptions", type: "text", desc: "Assumptions" },
      { name: "warranty", type: "text", desc: "Warranty terms" },
      { name: "start_date", type: "string", desc: "Start date" },
      { name: "completion_date", type: "string", desc: "Completion date" },
      { name: "prepared_by", type: "string", desc: "Prepared by" },
      { name: "cmi_rep", type: "string", desc: "CMI representative" },
      { name: "notes", type: "text", desc: "Notes" },
    ],
  },
  {
    key: "blog_post", label: "Blog Post", plural: "blog posts", table: "blog_posts",
    description: "Blog/news articles (also sync to WordPress).",
    idColumn: "id", slugFrom: "title", hasUpdatedAt: true, searchColumns: ["title", "category"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: CONTENT,
    fields: [
      { name: "title", type: "string", desc: "Post title", required: true },
      { name: "slug", type: "string", desc: "URL slug (auto from title if blank)" },
      { name: "category", type: "string", desc: "Category" },
      { name: "excerpt", type: "text", desc: "Short excerpt" },
      { name: "content", type: "text", desc: "Body content (HTML/markdown)" },
      { name: "featured_image", type: "string", desc: "Featured image URL" },
      { name: "tags", type: "string[]", desc: "Tags" },
      { name: "author", type: "string", desc: "Author name" },
      { name: "status", type: "enum", desc: "Publish status", enumValues: ["draft", "published", "scheduled", "archived"] },
      { name: "published_at", type: "date", desc: "Publish date" },
    ],
  },
  {
    key: "email_template", label: "Email Template", plural: "email templates", table: "email_templates",
    description: "Reusable email templates for the communications composer.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["name", "subject"],
    orderBy: { column: "updated_at", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "name", type: "string", desc: "Template name", required: true },
      { name: "subject", type: "string", desc: "Email subject" },
      { name: "preview_text", type: "string", desc: "Inbox preview text" },
      { name: "builder_type", type: "enum", desc: "How it's built", enumValues: ["visual", "html"] },
      { name: "html", type: "text", desc: "Rendered HTML body" },
      { name: "trigger_event", type: "string", desc: "Automation trigger, if any" },
      { name: "status", type: "string", desc: "Status (active/draft)" },
    ],
  },
  {
    key: "portfolio_item", label: "Portfolio Item", plural: "portfolio items", table: "portfolio",
    description: "Public portfolio/showcase projects.",
    idColumn: "id", slugFrom: "title", hasUpdatedAt: true, searchColumns: ["title", "category", "location"],
    orderBy: { column: "sort_order", ascending: true }, writeRoles: CONTENT,
    fields: [
      { name: "title", type: "string", desc: "Project title", required: true },
      { name: "slug", type: "string", desc: "URL slug" },
      { name: "subtitle", type: "string", desc: "Subtitle" },
      { name: "category", type: "string", desc: "Category" },
      { name: "location", type: "string", desc: "Location" },
      { name: "timeline", type: "string", desc: "Timeline" },
      { name: "year", type: "number", desc: "Year completed" },
      { name: "square_feet", type: "number", desc: "Square footage" },
      { name: "description", type: "text", desc: "Description" },
      { name: "featured_image", type: "string", desc: "Featured image URL" },
      { name: "services_used", type: "string[]", desc: "Services used" },
      { name: "tags", type: "string[]", desc: "Tags" },
      { name: "status", type: "enum", desc: "Status", enumValues: ["draft", "published", "hidden", "archived"] },
      { name: "is_featured", type: "boolean", desc: "Featured on site" },
      { name: "client_visible", type: "boolean", desc: "Visible to clients" },
    ],
  },
  {
    key: "team_member", label: "Team Member", plural: "team members", table: "team_members",
    description: "Public team/staff directory profiles.",
    idColumn: "id", slugFrom: "name", hasUpdatedAt: true, searchColumns: ["name", "role", "department"],
    orderBy: { column: "sort_order", ascending: true }, writeRoles: A,
    fields: [
      { name: "name", type: "string", desc: "Full name", required: true },
      { name: "role", type: "string", desc: "Job role/title" },
      { name: "department", type: "string", desc: "Department" },
      { name: "bio", type: "text", desc: "Biography" },
      { name: "tagline", type: "string", desc: "Short tagline" },
      { name: "email", type: "string", desc: "Email" },
      { name: "phone", type: "string", desc: "Phone" },
      { name: "profile_photo", type: "string", desc: "Photo URL" },
      { name: "attributes", type: "string[]", desc: "Attribute tags" },
      { name: "availability", type: "string", desc: "Availability note" },
      { name: "sort_order", type: "number", desc: "Sort order" },
      { name: "status", type: "enum", desc: "Status", enumValues: ["active", "inactive"] },
    ],
  },
  {
    key: "selection", label: "Project Selection", plural: "selections", table: "project_selections",
    description: "Client material/product selections for projects.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["name", "project_name", "category"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "name", type: "string", desc: "Selection name", required: true },
      { name: "project_id", type: "string", desc: "Project id" },
      { name: "project_name", type: "string", desc: "Project name" },
      { name: "room_area_name", type: "string", desc: "Room/area" },
      { name: "category", type: "string", desc: "Category" },
      { name: "custom_product_name", type: "string", desc: "Custom product name" },
      { name: "description", type: "text", desc: "Description" },
      { name: "selection_status", type: "string", desc: "Selection status" },
      { name: "approval_status", type: "string", desc: "Approval status" },
      { name: "procurement_status", type: "string", desc: "Procurement status" },
      { name: "install_status", type: "string", desc: "Install status" },
      { name: "quantity", type: "number", desc: "Quantity" },
      { name: "estimated_cost", type: "number", desc: "Estimated cost" },
      { name: "client_price", type: "number", desc: "Client price" },
      { name: "client_visible", type: "boolean", desc: "Visible to client" },
      { name: "internal_notes", type: "text", desc: "Internal notes" },
    ],
  },
  {
    key: "product", label: "Product", plural: "products", table: "products",
    description: "Product catalog used for selections.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["product_name", "brand", "sku"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "product_name", type: "string", desc: "Product name", required: true },
      { name: "category", type: "string", desc: "Category" },
      { name: "brand", type: "string", desc: "Brand" },
      { name: "manufacturer", type: "string", desc: "Manufacturer" },
      { name: "sku", type: "string", desc: "SKU" },
      { name: "model_number", type: "string", desc: "Model number" },
      { name: "description", type: "text", desc: "Description" },
      { name: "unit_cost", type: "number", desc: "Unit cost" },
      { name: "retail_price", type: "number", desc: "Retail price" },
      { name: "availability_status", type: "enum", desc: "Availability", enumValues: ["available", "limited", "out_of_stock", "discontinued", "special_order", "unknown"] },
      { name: "lead_time_days", type: "number", desc: "Lead time (days)" },
      { name: "product_url", type: "string", desc: "Product URL" },
      { name: "image_url", type: "string", desc: "Image URL" },
    ],
  },
  {
    key: "booking", label: "Booking / Appointment", plural: "bookings", table: "booking_appointments",
    description: "Scheduled appointments and consultations.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["title", "customer_email", "customer_first_name", "customer_last_name"],
    orderBy: { column: "start_time", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "title", type: "string", desc: "Appointment title" },
      { name: "customer_first_name", type: "string", desc: "Customer first name" },
      { name: "customer_last_name", type: "string", desc: "Customer last name" },
      { name: "customer_email", type: "string", desc: "Customer email" },
      { name: "customer_phone", type: "string", desc: "Customer phone" },
      { name: "start_time", type: "date", desc: "Start time (ISO)", required: true },
      { name: "end_time", type: "date", desc: "End time (ISO)" },
      { name: "status", type: "enum", desc: "Status", enumValues: ["pending", "confirmed", "rescheduled", "canceled", "completed", "no_show"] },
      { name: "location_type", type: "string", desc: "Location type" },
      { name: "meeting_url", type: "string", desc: "Meeting URL" },
      { name: "customer_notes", type: "text", desc: "Customer notes" },
      { name: "internal_notes", type: "text", desc: "Internal notes" },
      { name: "client_visible", type: "boolean", desc: "Visible to client" },
    ],
  },
  {
    key: "business_card", label: "Business Card", plural: "business cards", table: "business_cards",
    description: "Digital business cards (scalar fields; use the builder for sections/links).",
    idColumn: "id", slugFrom: "card_name", hasUpdatedAt: true, searchColumns: ["card_name", "display_name", "slug"],
    orderBy: { column: "updated_at", ascending: false }, writeRoles: A,
    fields: [
      { name: "card_name", type: "string", desc: "Internal card name", required: true },
      { name: "slug", type: "string", desc: "Public slug" },
      { name: "status", type: "enum", desc: "Status", enumValues: ["draft", "published", "unpublished", "archived"] },
      { name: "staff_user_id", type: "string", desc: "Owner staff user id" },
      { name: "display_name", type: "string", desc: "Display name" },
      { name: "job_title", type: "string", desc: "Job title" },
      { name: "company_name", type: "string", desc: "Company" },
      { name: "bio", type: "text", desc: "Bio" },
      { name: "primary_phone", type: "string", desc: "Phone" },
      { name: "primary_email", type: "string", desc: "Email" },
      { name: "website_url", type: "string", desc: "Website" },
      { name: "nfc_status", type: "string", desc: "NFC status" },
    ],
  },
  {
    key: "contact_submission", label: "Contact Form Submission", plural: "contact submissions", table: "contact_submissions",
    description: "Inbound contact-form submissions from the public website.",
    idColumn: "id", searchColumns: ["first_name", "last_name", "email", "subject"],
    orderBy: { column: "submitted_at", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "first_name", type: "string", desc: "First name" },
      { name: "last_name", type: "string", desc: "Last name" },
      { name: "email", type: "string", desc: "Email" },
      { name: "phone", type: "string", desc: "Phone" },
      { name: "subject", type: "string", desc: "Subject" },
      { name: "message", type: "text", desc: "Message" },
      { name: "status", type: "enum", desc: "Status", enumValues: ["new", "read", "archived"] },
    ],
  },
  {
    key: "message", label: "Message Log", plural: "messages", table: "messages",
    description: "Logged emails, SMS, and calls. To SEND email/SMS use the send_message tool, not create.",
    idColumn: "id", searchColumns: ["to_address", "from_address", "subject"],
    orderBy: { column: "sent_at", ascending: false }, writeRoles: OPS,
    fields: [
      { name: "direction", type: "enum", desc: "Direction", enumValues: ["outbound", "inbound"] },
      { name: "channel", type: "enum", desc: "Channel", enumValues: ["email", "sms", "call"] },
      { name: "to_address", type: "string", desc: "Recipient" },
      { name: "from_address", type: "string", desc: "Sender" },
      { name: "subject", type: "string", desc: "Subject (email)" },
      { name: "body", type: "text", desc: "Message body" },
      { name: "status", type: "string", desc: "Delivery status" },
      { name: "contact_id", type: "string", desc: "Linked contact id" },
    ],
  },
  {
    key: "user", label: "Staff User", plural: "staff users", table: "staff_users",
    description: "Staff accounts and roles. Sensitive — admin only.",
    idColumn: "id", hasUpdatedAt: true, searchColumns: ["email", "display_name", "first_name", "last_name"],
    orderBy: { column: "created_at", ascending: false }, writeRoles: A, deleteRoles: ["super_admin"],
    fields: [
      { name: "email", type: "string", desc: "Email", required: true },
      { name: "first_name", type: "string", desc: "First name", required: true },
      { name: "last_name", type: "string", desc: "Last name", required: true },
      { name: "display_name", type: "string", desc: "Display name" },
      { name: "phone", type: "string", desc: "Phone" },
      { name: "role_slug", type: "enum", desc: "Role", enumValues: ["super_admin", "admin", "project_manager", "staff", "designer", "estimator", "superintendent", "subcontractor", "vendor", "client", "viewer"] },
      { name: "status", type: "enum", desc: "Account status", enumValues: ["active", "invited", "pending", "disabled", "removed", "suspended", "archived"] },
      { name: "title", type: "string", desc: "Title" },
      { name: "company_name", type: "string", desc: "Company" },
      { name: "job_title", type: "string", desc: "Job title" },
      { name: "notes", type: "text", desc: "Notes" },
    ],
  },
];

export function getEntity(key: string): AgentEntity | undefined {
  return ENTITIES.find((e) => e.key === key || e.plural === key || e.table === key);
}

export function entityOverview(): string {
  return ENTITIES.map((e) => `- ${e.key}: ${e.description}`).join("\n");
}
